### ISSUE TITLE
Add reverse proxy "slides.lobid.org"

### ISSUE THREAD

**Issue by dr0i** [hbz/hbz.github.com#10]
Let our webserver handle the proxying , analog to https://github.com/lobid/lobid.github.com/issues/12.

- [x] configure apache
- [x] get rid of cname entry
- [x] get rid of github specific settings

**Comment by acka47** [comment]
http://slides.lobid.org currently isn't working. @dr0i, please have a look.

**Comment by acka47** [comment]
You probably got something wrong. Slides aren't in this repo but at https://github.com/hbz/slides.

**Comment by dr0i** [comment]
Should work now. Mind the cache of your browser when testing.

**Comment by acka47** [comment]
+1 (Reviewing this made me open https://github.com/hbz/slides/issues/7.)

**Comment by acka47** [comment]
Closing.
