### ISSUE TITLE
Offer overview of presentations 

### ISSUE THREAD

**Issue by acka47** [hbz/hbz.github.com#3]
At http://hbz.github.io/slides/ there should be an overview page listing all presentations from most recent to oldest.

We might build this by adding schema.org markup to all slidedecks and using this for the overview.

**Comment by TobiasNx** [comment]
@acka47 it seems that the page has already an "overview page listing all presentations from most recent to oldest"

Can this issue be closed?

**Comment by acka47** [comment]
> Can this issue be closed?

Yes, thanks for the hint. Closing.
